name: import_rules
description: |
  A lint plugin for the Dart analyzer that enforces custom import rules in your projects.
  enabling everything from simple allow/disallow lists to complex module dependency constraints 
  for architectural patterns such as layered architecture, feature isolation, and encapsulation.
version: 0.0.4
repository: https://github.com/fujidaiti/import_rules.git

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_plugin: ^0.3.3
  analyzer: ^8.0.0
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3
  logging: ^1.3.0
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
